# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdoptingHay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'FirebaseFirestoreSwift', '8.3.0-beta'

  # Pods for AdoptingHay

end
